build:
    sudo podman build -t quay.io/fedora/fedora-coreos:42.20250705.3.0-trustee -f Containerfile .

oci-archive:
    sudo skopeo copy containers-storage:quay.io/fedora/fedora-coreos:42.20250705.3.0-trustee oci-archive:fedora-coreos-42.20250705.3.0-trustee.ociarchive

cosa-qemu:
    # TODO cosa init
    cosa import oci-archive:fedora-coreos-42.20250705.3.0-trustee.ociarchive
    cosa osbuild qemu

osbuild-qemu:
    #!/bin/bash
    set -euo pipefail

    TMPDIR=$(mktemp -d)
    git clone --depth 1 https://github.com/coreos/custom-coreos-disk-images ${TMPDIR}

    sudo -E ${TMPDIR}/custom-coreos-disk-images.sh --platform qemu \
        --ociarchive oci-archive:fedora-coreos-42.20250705.3.0-trustee.ociarchive \
        --osname fedora-coreos
    rm -rf "$TMPDIR"
    sudo chown $USER:$USER fedora-coreos-42.20250705.3.0-trustee-qemu.x86_64.qcow2
