FROM quay.io/afrosi_rh/kbs-client-image:latest as kbc
FROM quay.io/fedora/fedora-coreos:stable

USER root
COPY initrd-trustee_plus/dracut/dracut.conf /etc/dracut.conf
COPY initrd-trustee_plus/dracut/65aaclient /usr/lib/dracut/modules.d/65aaclient
COPY initrd-trustee_plus/scripts/aa-client-service.sh /usr/bin/aa-client-service.sh
COPY initrd-trustee_plus/systemd/aa-client.service /usr/lib/systemd/system/aa-client.service
COPY --from=kbc /usr/local/bin/kbs-client /usr/bin/trustee-attester

RUN chmod +x /usr/bin/aa-client-service.sh
RUN set -xeuo pipefail && \
    KERNEL_VERSION="$(basename $(ls -d /lib/modules/*))" && \
    raw_args="$(	lsinitrd /lib/modules/${KERNEL_VERSION}/initramfs.img | grep '^Arguments: ' | sed 's/^Arguments: //')" && \
    stock_arguments=$(echo "$raw_args" | sed "s/'//g") && \
    echo "Using kernel: $KERNEL_VERSION" && \
    echo "Arguments: $stock_arguments" && \
    mkdir -p /tmp/dracut /var/roothome && \
    dracut $stock_arguments && \
    mv -v "/lib/modules/${KERNEL_VERSION}/initramfs.img" "/lib/modules/${KERNEL_VERSION}/initramfs.stock.img" && \
    mv -v /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img" && \
    ostree container commit

RUN lsinitrd /lib/modules/*/initramfs.img | grep "aa-client"
