# from 419.96.202505021444-0-coreos 
FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cfe9b9725b99707b25774a32d739ec121a699d43d7fb398f1ace82b041021864

USER root
COPY initrd-trustee_plus/dracut/dracut.conf /etc/dracut.conf
COPY initrd-trustee_plus/dracut/65aaclient /usr/lib/dracut/modules.d/65aaclient
COPY initrd-trustee_plus/scripts/aa-client-service.sh /usr/bin/aa-client-service.sh
COPY initrd-trustee_plus/systemd/aa-client.service /usr/lib/systemd/system/aa-client.service
COPY trustee-attester /usr/bin/trustee-attester

RUN set -xeuo pipefail && \
    KERNEL_VERSION="$(basename $(ls -d /lib/modules/*))" && \
    raw_args="$(	lsinitrd /lib/modules/${KERNEL_VERSION}/initramfs.img | grep '^Arguments: ' | sed 's/^Arguments: //')" && \
    stock_arguments=$(echo "$raw_args" | sed "s/'//g") && \
    echo "Using kernel: $KERNEL_VERSION" && \
    echo "Arguments: $stock_arguments" && \
    mkdir -p /tmp/dracut /var/roothome && \
    dracut $stock_arguments && \
    mv -v "/lib/modules/${KERNEL_VERSION}/initramfs.img" "/lib/modules/${KERNEL_VERSION}/initramfs.stock.img" && \
    mv -v /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img" && \
    ostree container commit

RUN lsinitrd /lib/modules/*/initramfs.img | grep "aa-client"