name: "Build and Push Trustee Image"

env:
  NAME: "trustee"
  REGISTRY: "quay.io/yalzhang"

on:
  push:
    branches:
      - main
    paths:
      - 'configs/trustee/containers/trustee.container'
      - '.github/workflows/build-trustee.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'configs/trustee/containers/trustee.container'
      - '.github/workflows/build-trustee.yml'
  workflow_dispatch:

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-trustee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build trustee image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            configs/trustee/containers/trustee.container
          context: configs/trustee/containers/
          oci: true

      - name: Push to Quay.io
        uses: redhat-actions/push-to-registry@v2
        # if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
